version: "3.8"

services:
  frontend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    image: frontend_app_image
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage        # dossier pour stockage local si nécessaire
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "ta_valeur_ici"
      CLERK_SECRET_KEY: "ta_valeur_ici"
      SIGNING_SECRET: "ta_valeur_ici"
      NEXT_PUBLIC_WS_URL: "http://109.199.107.23:4000/api/v1"  # utiliser le nom du conteneur backend
    restart: always
    networks:
      - microservices-net
      - dockerfiles_microservices-net

networks:
  microservices-net:
    external: true
  dockerfiles_microservices-net:
    external: true
