import { User, Wallet, Order, Transaction, Trip, PaymentMethod, TransactionType, OrderStatus, TripStatus } from "../types/schemaTypes";

export const fakeWallet: Wallet = {
    id: "wallet-123",
    balance: 125000, // en centimes
    userId: "user-123",
    paymentMethod: PaymentMethod.MOBILE_MONEY,
    rechargeType: "WAVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    transactions: [],
};

export const fakeTransactions: Transaction[] = [
    {
        id: "txn-1",
        amount: 10000,
        type: TransactionType.DEPOSIT,
        walletId: "wallet-123",
        userId: "user-123",
        reference: "ref-abc",
        description: "Recharge wallet",
        createdAt: new Date(Date.now() - 86400000 * 3),
        updatedAt: new Date(),
    },
    {
        id: "txn-2",
        amount: -1800,
        type: TransactionType.COMMISSION,
        walletId: "wallet-123",
        userId: "user-123",
        reference: "order-789",
        description: "Commission 18% sur commande",
        createdAt: new Date(Date.now() - 86400000 * 1),
        updatedAt: new Date(),
    },
];

export const fakeOrders: Order[] = [
    {
        id: "order-1",
        userId: "user-123",
        tripId: "trip-1",
        status: OrderStatus.COMPLETED,
        paymentMethod: PaymentMethod.MOBILE_MONEY,
        amount: 1200,
        canceledAt: null,
        createdAt: new Date(Date.now() - 86400000 * 7),
        completedAt: new Date(Date.now() - 86400000 * 6),
        updatedAt: new Date(),
    },
    {
        id: "order-2",
        userId: "user-123",
        tripId: "trip-2",
        status: OrderStatus.PENDING,
        paymentMethod: PaymentMethod.CARD,
        amount: 2300,
        canceledAt: null,
        createdAt: new Date(Date.now() - 86400000 * 2),
        completedAt: null,
        updatedAt: new Date(),
    },
];

export const fakeTrips: Trip[] = [
    {
        id: "trip-1",
        createdById: "user-123",
        driverId: "driver-1",
        vehicleId: "vehicle-1",
        departure: "Abidjan",
        departureLatitude: 5.345,
        departureLongitude: -4.024,
        arrival: "Yamoussoukro",
        arrivalLatitude: 6.816,
        arrivalLongitude: -5.277,
        date: new Date(),
        departureTime: "08:00",
        arrivalTime: "12:00",
        estimatedArrival: new Date(Date.now() + 4 * 3600 * 1000),
        availableSeats: 3,
        distance: 230,
        price: 15000,
        description: "Trajet rapide",
        instructions: "Arriver à l’heure",
        status: TripStatus.COMPLETED,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "trip-2",
        createdById: "user-123",
        driverId: "driver-2",
        vehicleId: "vehicle-2",
        departure: "Bouaké",
        departureLatitude: 7.7,
        departureLongitude: -5.03,
        arrival: "Korhogo",
        arrivalLatitude: 9.45,
        arrivalLongitude: -5.61,
        date: new Date(),
        departureTime: "14:00",
        arrivalTime: "18:00",
        estimatedArrival: new Date(Date.now() + 4 * 3600 * 1000),
        availableSeats: 5,
        distance: 270,
        price: 20000,
        description: "Trajet confortable",
        instructions: null,
        status: TripStatus.PENDING,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
