import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en"  suppressHydrationWarning>
      
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // style={{
        //   backgroundImage: 'url("/v1045-06a.jpg")',
        //   backgroundSize: 'cover',
        //   backgroundPosition: 'center',
        //   backgroundRepeat: 'no-repeat',
        //   backgroundAttachment: 'fixed',
        // }} 
  >
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </body>
      </html>
  );
}
