// mockOrders.ts

import { DeliveryMethod, OrderStatus, PaymentMethod, Role, UserStatus } from "@/types/AllTypes";
import { EcommerceOrderResponse } from "@/types/ApiReponse/EcommerceOrderResponse";

export const mockOrders: EcommerceOrderResponse = {
    data: [
        {
            id: "1",
            ordersNumber: "CMD-0001",
            userId: "u1",
            status: OrderStatus.COMPLETED,
            paymentMethod: PaymentMethod.MOBILE_MONEY,
            deliveryMethod: DeliveryMethod.HOME_DELIVERY,
            amount: 3500,
            canceledAt: null,
            createdAt: "2025-07-01T12:33:00Z",
            updatedAt: "2025-07-01T12:35:00Z",
            addedById: "admin1",
            items: [
                {
                    id: "i1",
                    ecommerceOrderId: "1",
                    productId: "p1",
                    quantity: 2,
                    price: 1500,
                    product: {
                        id: "p1",
                        name: "Banane Plantain",
                        description: "Banane plantain fraîche",
                        price: 1500,
                        stock: 100,
                        sku: "BP-001",
                        imageUrl: "/banana.jpg",
                        createdAt: "2025-06-01T10:00:00Z",
                        updatedAt: "2025-06-10T10:00:00Z",
                        categoryId: "c1",
                        serviceId: "s1",
                        addedById: "admin1",
                    },
                },
            ],
            user: {
                id: "u1",
                email: "client@example.com",
                password: "hashedpassword",
                passwordGenerate: null,
                name: "Jean Dupont",
                role: Role.USER,
                status: UserStatus.ACTIVE,
                phoneCountryCode: "+225",
                phoneNumber: "0102030405",
                createdAt: "2025-05-01T08:00:00Z",
                updatedAt: "2025-05-10T08:00:00Z",
                partnerId: null,
            },
        },
        {
            id: "2",
            ordersNumber: "CMD-0002",
            userId: "u2",
            status: OrderStatus.CANCELLED,
            paymentMethod: PaymentMethod.MOBILE_MONEY,
            deliveryMethod: DeliveryMethod.HOME_DELIVERY,
            amount: 0,
            canceledAt: "2025-07-02T09:44:00Z",
            createdAt: "2025-07-02T09:40:00Z",
            updatedAt: "2025-07-02T09:45:00Z",
            addedById: "admin2",
            items: [],
            user: {
                id: "u2",
                email: "client2@example.com",
                password: "hashedpassword",
                passwordGenerate: null,
                name: "Marie Koffi",
                role: Role.USER,
                status: UserStatus.ACTIVE,
                phoneCountryCode: "+225",
                phoneNumber: "0506070809",
                createdAt: "2025-05-05T08:00:00Z",
                updatedAt: "2025-05-15T08:00:00Z",
                partnerId: null,
            },
        },
    ],
};
